name: construir imagen y subirla a DockeHub

on:
    push: 
        branches: ["main"]
    pull_request:
        branches: ["main"]   

jobs: 

    build:
        runs-on: ubuntu-lastest
        steps:
            - uses: actions/checkout@v3
            - name: Login en Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Preparar construcción con Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Construir imagen y subirla a Docker Hub
              uses: docker/build-push-action@v4
              with: 
                context: .
                file: ./Dockerfile
                push: true
                tags: |
                 ${{ secrets.DOCKERHUB_USERNAME }}/docker-github-actions:lastet
                 ${{ secrets.DOCKERHUB_USERNAME }}/docker-github-actions:${{ github.sha }}